### ISSUE TITLE
When I added wavevit to mmdetection, the training made an error

### ISSUE THREAD

**Issue by liujia2020** [YehLi/ImageNetModel#2]
2022-08-26 19:04:36,938 - mmdet - INFO - workflow: [('train', 1)], max: 150 epochs
2022-08-26 19:04:36,938 - mmdet - INFO - Checkpoints will be saved to G:\Code\mmdetection-2.25.1\work_dirs\Version2\RetinaNet_WaveVit by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 238, in main
    meta=meta)
  File "g:\code\mmdetection-2.25.1\mmdet\apis\train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "g:\code\mmdetection-2.25.1\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\mmcv\runner\fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "g:\code\mmdetection-2.25.1\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "g:\code\mmdetection-2.25.1\mmdet\models\detectors\single_stage.py", line 82, in forward_train
    x = self.extract_feat(img)
  File "g:\code\mmdetection-2.25.1\mmdet\models\detectors\single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "g:\code\mmdetection-2.25.1\mmdet\models\backbones\wavevit.py", line 490, in forward
    x = self.forward_features(x)
  File "g:\code\mmdetection-2.25.1\mmdet\models\backbones\wavevit.py", line 483, in forward_features
    x = blk(x, H, W)
  File "E:\Anaconda3\envs\new_water\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "g:\code\mmdetection-2.25.1\mmdet\models\backbones\wavevit.py", line 321, in forward
    x = x + self.drop_path(self.attn(self.norm1(x), H, W))
  File "E:\Anaconda3\envs\new_water\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "g:\code\mmdetection-2.25.1\mmdet\models\backbones\wavevit.py", line 224, in forward
    x_dwt = self.dwt(self.reduce(x))
  File "E:\Anaconda3\envs\new_water\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "g:\code\mmdetection-2.25.1\mmdet\models\backbones\wavevit.py", line 123, in forward
    return DWT_Function.apply(x, self.w_ll, self.w_lh, self.w_hl, self.w_hh)
  File "g:\code\mmdetection-2.25.1\mmdet\models\backbones\wavevit.py", line 23, in forward
    x_ll = torch.nn.functional.conv2d(x, w_ll.expand(dim, -1, -1, -1), stride=2, groups=dim)
RuntimeError: expected scalar type Float but found Half

**Comment by hayatrajani** [comment]
Changing **float16** to **float32** in classes [DWT_2D](https://github.com/YehLi/ImageNetModel/blob/main/classification/torch_wavelets.py#L110) and [IDWT_2D](https://github.com/YehLi/ImageNetModel/blob/main/classification/torch_wavelets.py#L88) fixes the issue for me.

**Comment by liujia2020** [comment]
> Changing **float16** to **float32** in classes [DWT_2D](https://github.com/YehLi/ImageNetModel/blob/main/classification/torch_wavelets.py#L110) and [IDWT_2D](https://github.com/YehLi/ImageNetModel/blob/main/classification/torch_wavelets.py#L88) fixes the issue for me.

Thank you, bro, you are really help me a lot. God bless you. You will be rich. You will have two girl friends~
